package oak;

import java.nio.ByteBuffer;
import java.util.*;
import java.util.concurrent.ConcurrentSkipListMap;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

public class OakMapOnHeapImpl implements OakMap {

    /*-------------- Members --------------*/

    final ConcurrentSkipListMap<ByteBuffer, Chunk> skiplist;    // skiplist of chunks for fast navigation
    private final AtomicReference<Chunk> head;
    private final ByteBuffer minKey;
    private final Comparator comparator;
    private final HandleFactory handleFactory;
    private final ValueFactory valueFactory;

    /**
     * Lazily initialized descending key set
     */
    private OakMap descendingMap;

    /*-------------- Constructors --------------*/

    public OakMapOnHeapImpl() {
        ByteBuffer bb = ByteBuffer.allocate(1).put(Byte.MIN_VALUE);
        bb.rewind();
        this.minKey = bb;
        this.comparator = new ByteBufferComparator();

        this.skiplist = new ConcurrentSkipListMap<>();
        Chunk head = new Chunk(this.minKey, null, this.comparator, null);
        this.skiplist.put(head.minKey, head);    // add first chunk (head) into skiplist
        this.head = new AtomicReference<>(head);

        this.descendingMap = null;
        this.handleFactory = new HandleFactory(false);
        valueFactory = new ValueFactory(false);
    }

    public OakMapOnHeapImpl(Comparator<ByteBuffer> comparator, ByteBuffer minKey) {
        this.minKey = minKey;
        this.comparator = comparator;

        this.skiplist = new ConcurrentSkipListMap<>(comparator);
        Chunk head = new Chunk(this.minKey, null, comparator, null);
        this.skiplist.put(head.minKey, head);    // add first chunk (head) into skiplist
        this.head = new AtomicReference<>(head);

        this.descendingMap = null;
        this.handleFactory = new HandleFactory(false);
        valueFactory = new ValueFactory(false);
    }

    class ByteBufferComparator implements Comparator<ByteBuffer> {
        @Override
        public int compare(ByteBuffer bb1, ByteBuffer bb2) {
            return bb1.compareTo(bb2);
        }
    }

    /*-------------- Methods --------------*/

    /**
     * finds and returns the chunk where key should be located, starting from given chunk
     */
    private Chunk iterateChunks(Chunk c, ByteBuffer key) {
        // find chunk following given chunk (next)
        Chunk next = c.next.getReference();

        // since skiplist isn't updated atomically in split/compaction, our key might belong in the next chunk
        // we need to iterate the chunks until we find the correct one
        while ((next != null) && (comparator.compare(next.minKey, key) <= 0)) {
            c = next;
            next = c.next.getReference();
        }

        return c;
    }

    private Rebalancer.RebalanceResult rebalance(Chunk c, ByteBuffer opKey, ByteBuffer opValue, Consumer<WritableOakBuffer> function, Operation op) {
        if (c == null) {

            assert op == Operation.NO_OP;
            return null;
        }
        Rebalancer rebalancer = new Rebalancer(c, comparator, false, null, handleFactory, valueFactory);

        rebalancer = rebalancer.engageChunks(); // maybe we encountered a different rebalancer

        // freeze all the engaged range.
        // When completed, all update (put, next pointer update) operations on the engaged range
        // will be redirected to help the rebalance procedure
        rebalancer.freeze();

        Rebalancer.RebalanceResult result = rebalancer.createNewChunks(opKey, opValue, function, op); // split or compact
        // if returned true then this thread was responsible for the creation of the new chunks
        // and it inserted the put

        // lists may be generated by another thread
        List<Chunk> newChunks = rebalancer.getNewChunks();
        List<Chunk> engaged = rebalancer.getEngagedChunks();

        connectToChunkList(engaged, newChunks);

        updateIndexAndNormalize(engaged, newChunks);

        return result;
    }

    private void checkRebalance(Chunk c) {
        if (c.shouldRebalance()) {
            rebalance(c, null, null, null, Operation.NO_OP);
        }
    }

    private void connectToChunkList(List<Chunk> engaged, List<Chunk> children) {

        updateLastChild(engaged, children);

        Chunk firstEngaged = engaged.get(0);

        // replace in linked list - we now need to find previous chunk to our chunk
        // and CAS its next to point to c1, which is the same c1 for all threads who reached this point
        // since prev might be marked (in compact itself) - we need to repeat this until successful
        while (true) {
            // start with first chunk (i.e., head)
            Map.Entry<ByteBuffer, Chunk> lowerEntry = skiplist.lowerEntry(firstEngaged.minKey);

            Chunk prev = lowerEntry != null ? lowerEntry.getValue() : null;
            Chunk curr = (prev != null) ? prev.next.getReference() : null;

            // if didn't succeed to find prev through the skiplist - start from the head
            if (prev == null || curr != firstEngaged) {
                prev = null;
                curr = skiplist.firstEntry().getValue();
                // iterate until found chunk or reached end of list
                while ((curr != firstEngaged) && (curr != null)) {
                    prev = curr;
                    curr = curr.next.getReference();
                }
            }

            // chunk is head, we need to "add it to the list" for linearization point
            if (curr == firstEngaged && prev == null) {
                this.head.compareAndSet(firstEngaged, children.get(0));
                break;
            }
            // chunk is not in list (someone else already updated list), so we're done with this part
            if ((curr == null) || (prev == null)) {
                break;
            }

            // if prev chunk is marked - it is deleted, need to help split it and then continue
            if (prev.next.isMarked()) {
                rebalance(prev, null, null, null, Operation.NO_OP);
                continue;
            }

            // try to CAS prev chunk's next - from chunk (that we split) into c1
            // c1 is the old chunk's replacement, and is already connected to c2
            // c2 is already connected to old chunk's next - so all we need to do is this replacement
            if ((prev.next.compareAndSet(firstEngaged, children.get(0), false, false)) ||
                    (!prev.next.isMarked())) {
                // if we're successful, or we failed but prev is not marked - so it means someone else was successful
                // then we're done with loop
                break;
            }
        }

    }

    private void updateLastChild(List<Chunk> engaged, List<Chunk> children) {
        Chunk lastEngaged = engaged.get(engaged.size() - 1);
        Chunk nextToLast = lastEngaged.markAndGetNext(); // also marks last engaged chunk as deleted
        Chunk lastChild = children.get(children.size() - 1);

        lastChild.next.compareAndSet(null, nextToLast, false, false);
    }

    private void updateIndexAndNormalize(List<Chunk> engagedChunks, List<Chunk> children) {
        Iterator<Chunk> iterEngaged = engagedChunks.iterator();
        Iterator<Chunk> iterChildren = children.iterator();

        Chunk firstEngaged = iterEngaged.next();
        Chunk firstChild = iterChildren.next();

        // need to make the new chunks available, before removing old chunks
        skiplist.replace(firstEngaged.minKey, firstEngaged, firstChild);

        // remove all old chunks from index.
        while (iterEngaged.hasNext()) {
            Chunk engagedToRemove = iterEngaged.next();
            skiplist.remove(engagedToRemove.minKey, engagedToRemove); // conditional remove is used
        }

        // now after removing old chunks we can start normalizing
        firstChild.normalize();
        // TODO do we still need this? oak.Chunk.unsafe.storeFence();
        // using fence so puts can continue working immediately on this chunk

        // for simplicity -  naive lock implementation
        // can be implemented without locks using versions on next pointer in skiplist
        while (iterChildren.hasNext()) {
            Chunk childToAdd;
            synchronized (childToAdd = iterChildren.next()) {
                if (childToAdd.state() == Chunk.State.INFANT) { // make sure it wasn't add before
                    skiplist.putIfAbsent(childToAdd.minKey, childToAdd);
                    childToAdd.normalize();
                }
                // has a built in fence, so no need to add one here
            }
        }
    }

    private boolean rebalancePutIfAbsent(Chunk c, ByteBuffer key, ByteBuffer value) {
        Rebalancer.RebalanceResult result = rebalance(c, key, value, null, Operation.PUT_IF_ABSENT);
        assert result != null;
        if (!result.success) { // rebalance helped put
            return putIfAbsent(key, value);
        }
        return result.putIfAbsent;
    }

    private void rebalancePut(Chunk c, ByteBuffer key, ByteBuffer value) {
        Rebalancer.RebalanceResult result = rebalance(c, key, value, null, Operation.PUT);
        assert result != null;
        if (result.success) { // rebalance helped put
            return;
        }
        put(key, value);
    }

    private void rebalanceCompute(Chunk c, ByteBuffer key, ByteBuffer value, Supplier<ByteBuffer> constructor, Consumer<WritableOakBuffer> function) {
        Rebalancer.RebalanceResult result = rebalance(c, key, value, function, Operation.COMPUTE);
        assert result != null;
        if (result.success) { // rebalance helped compute
            return;
        }
        putIfAbsentComputeIfPresent(key, constructor, function);
    }

    private boolean rebalanceRemove(Chunk c, ByteBuffer key) {
        Rebalancer.RebalanceResult result = rebalance(c, key, null, null, Operation.REMOVE);
        assert result != null;
        return result.success;
    }

    /*-------------- oak.OakMap Methods --------------*/

    @Override
    public void put(ByteBuffer key, ByteBuffer value) {
        if (key == null || value == null || key.remaining() == 0 || value.remaining() == 0) {
            throw new NullPointerException();
        }

        // find chunk matching key
        Chunk c = skiplist.floorEntry(key).getValue();
        c = iterateChunks(c, key);

        Chunk.LookUp lookUp = c.lookUp(key);
        if (lookUp != null && lookUp.handle != null) {
            lookUp.handle.put(value, null);
            return;
        }

        // if chunk is frozen or infant, we can't add to it
        // we need to help rebalancer first, then proceed
        Chunk.State state = c.state();
        if (state == Chunk.State.INFANT) {
            // the infant is already connected so rebalancer won't add this put
            rebalance(c.creator(), null, null, null, Operation.NO_OP);
            put(key, value);
            return;
        }
        if (state == Chunk.State.FROZEN || state == Chunk.State.RELEASED) {
            rebalancePut(c, key, value);
            return;
        }

        int ei = -1;
        int prevHi = -1;
        if (lookUp != null) {
            assert lookUp.handle == null;
            ei = lookUp.entryIndex;
            assert ei > 0;
            prevHi = lookUp.handleIndex;
        }

        if (ei == -1) {
            ei = c.allocateEntryAndKey(key);
            if (ei == -1) {
                rebalancePut(c, key, value);
                return;
            }
            ei = c.linkEntry(ei, key, true);
        }

        int hi = c.allocateHandle(handleFactory);
        if (hi == -1) {
            rebalancePut(c, key, value);
            return;
        }

        c.writeValue(hi, valueFactory.createValue(value, null)); // write value in place

        Chunk.OpData opData = new Chunk.OpData(Operation.PUT, ei, hi, prevHi, null);

        // publish put
        if (!c.publish(opData)) {
            rebalancePut(c, key, value);
            return;
        }

        // set pointer to value
        c.pointToValue(opData);

        c.unpublish(opData);

        checkRebalance(c);

    }

    @Override
    public boolean putIfAbsent(ByteBuffer key, ByteBuffer value) {
        if (key == null || value == null || key.remaining() == 0 || value.remaining() == 0) {
            throw new NullPointerException();
        }

        // find chunk matching key
        Chunk c = skiplist.floorEntry(key).getValue();
        c = iterateChunks(c, key);

        Chunk.LookUp lookUp = c.lookUp(key);
        if (lookUp != null && lookUp.handle != null) return false;

        // if chunk is frozen or infant, we can't add to it
        // we need to help rebalancer first, then proceed
        Chunk.State state = c.state();
        if (state == Chunk.State.INFANT) {
            // the infant is already connected so rebalancer won't add this put
            rebalance(c.creator(), null, null, null, Operation.NO_OP);
            return putIfAbsent(key, value);
        }
        if (state == Chunk.State.FROZEN || state == Chunk.State.RELEASED) {
            return rebalancePutIfAbsent(c, key, value);
        }


        int ei = -1;
        int prevHi = -1;
        if (lookUp != null) {
            assert lookUp.handle == null;
            ei = lookUp.entryIndex;
            assert ei > 0;
            prevHi = lookUp.handleIndex;
        }

        if (ei == -1) {
            ei = c.allocateEntryAndKey(key);
            if (ei == -1) {
                return rebalancePutIfAbsent(c, key, value);
            }
            ei = c.linkEntry(ei, key, true);
        }

        int hi = c.allocateHandle(handleFactory);
        if (hi == -1) {
            return rebalancePutIfAbsent(c, key, value);
        }

        c.writeValue(hi, valueFactory.createValue(value, null)); // write value in place

        Chunk.OpData opData = new Chunk.OpData(Operation.PUT_IF_ABSENT, ei, hi, prevHi, null);

        // publish put
        if (!c.publish(opData)) {
            return rebalancePutIfAbsent(c, key, value);
        }

        // set pointer to value
        boolean ret = c.pointToValue(opData);

        c.unpublish(opData);

        checkRebalance(c);

        return ret;
    }

    @Override
    public boolean putIfAbsent(ByteBuffer key, Consumer<ByteBuffer> valueCreator, int capacity) {
        throw new UnsupportedOperationException();
    }

    @Override
    public void putIfAbsentComputeIfPresent(ByteBuffer key, Supplier<ByteBuffer> constructor, Consumer<WritableOakBuffer> function) {
        if (key == null || key.remaining() == 0 || constructor == null || function == null) {
            throw new NullPointerException();
        }

        // find chunk matching key
        Chunk c = skiplist.floorEntry(key).getValue();
        c = iterateChunks(c, key);

        Chunk.LookUp lookUp = c.lookUp(key);
        if (lookUp != null && lookUp.handle != null) {
            lookUp.handle.compute(function, null);
            return;
        }

        ByteBuffer value = constructor.get();
        if (value == null || value.remaining() == 0) {
            throw new NullPointerException();
        }

        // if chunk is frozen or infant, we can't add to it
        // we need to help rebalancer first, then proceed
        Chunk.State state = c.state();
        if (state == Chunk.State.INFANT) {
            // the infant is already connected so rebalancer won't add this put
            rebalance(c.creator(), null, null, null, Operation.NO_OP);
            putIfAbsentComputeIfPresent(key, constructor, function);
            return;
        }
        if (state == Chunk.State.FROZEN || state == Chunk.State.RELEASED) {
            rebalanceCompute(c, key, value, constructor, function);
            return;
        }

        int ei = -1;
        int prevHi = -1;
        if (lookUp != null) {
            assert lookUp.handle == null;
            ei = lookUp.entryIndex;
            assert ei > 0;
            prevHi = lookUp.handleIndex;
        }

        if (ei == -1) {
            ei = c.allocateEntryAndKey(key);
            if (ei == -1) {
                rebalanceCompute(c, key, value, constructor, function);
                return;
            }
            ei = c.linkEntry(ei, key, true);
        }

        int hi = c.allocateHandle(handleFactory);
        if (hi == -1) {
            rebalanceCompute(c, key, value, constructor, function);
            return;
        }

        c.writeValue(hi, valueFactory.createValue(value, null)); // write value in place

        Chunk.OpData opData = new Chunk.OpData(Operation.COMPUTE, ei, hi, prevHi, function);

        // publish put
        if (!c.publish(opData)) {
            rebalanceCompute(c, key, value, constructor, function);
            return;
        }

        // set pointer to value
        c.pointToValue(opData);

        c.unpublish(opData);

        checkRebalance(c);

    }

    @Override
    public void putIfAbsentComputeIfPresent(ByteBuffer key, Consumer<ByteBuffer> valueCreator, int capacity, Consumer<WritableOakBuffer> function) {
        throw new UnsupportedOperationException();
    }

    @Override
    public void remove(ByteBuffer key) {
        if (key == null || key.remaining() == 0) {
            throw new NullPointerException();
        }

        boolean logical = true;
        Handle prev = null;

        while (true) {

            // find chunk matching key
            Chunk c = skiplist.floorEntry(key).getValue();
            c = iterateChunks(c, key);

            Chunk.LookUp lookUp = c.lookUp(key);
            if (lookUp != null && logical) {
                prev = lookUp.handle; // remember previous handle
            }
            if (!logical && lookUp != null && prev != lookUp.handle) {
                return;  // someone else used this entry
            }

            if (lookUp == null || lookUp.handle == null) return;

            if (logical) {
                if (!lookUp.handle.remove(null)) return;
            }

            // if chunk is frozen or infant, we can't add to it
            // we need to help rebalancer first, then proceed
            Chunk.State state = c.state();
            if (state == Chunk.State.INFANT) {
                // the infant is already connected so rebalancer won't add this put
                rebalance(c.creator(), null, null, null, Operation.NO_OP);
                logical = false;
                continue;
            }
            if (state == Chunk.State.FROZEN || state == Chunk.State.RELEASED) {
                if (!rebalanceRemove(c, key)) {
                    logical = false;
                    continue;
                }
                return;
            }


            assert lookUp.entryIndex > 0;
            assert lookUp.handleIndex > 0;
            Chunk.OpData opData = new Chunk.OpData(Operation.REMOVE, lookUp.entryIndex, -1, lookUp.handleIndex, null);

            // publish
            if (!c.publish(opData)) {
                if (!rebalanceRemove(c, key)) {
                    logical = false;
                    continue;
                }
                return;
            }

            // set pointer to value
            c.pointToValue(opData);

            c.unpublish(opData);

            checkRebalance(c);

            return;

        }
    }

    @Override
    public OakBuffer get(ByteBuffer key) {
        if (key == null || key.remaining() == 0) {
            throw new NullPointerException();
        }

        Chunk c = skiplist.floorEntry(key).getValue();
        c = iterateChunks(c, key);

        Chunk.LookUp lookUp = c.lookUp(key);
        return lookUp == null || lookUp.handle == null ? null : new OakBufferImpl(lookUp.handle);
    }

    @Override
    public <T> T getTransformation(ByteBuffer key, Function<ByteBuffer,T> transformer) {
        throw new UnsupportedOperationException();
    }

    public boolean computeIfPresent(ByteBuffer key, Consumer<WritableOakBuffer> function) {
        if (key == null || key.remaining() == 0 || function == null) {
            throw new NullPointerException();
        }

        Chunk c = skiplist.floorEntry(key).getValue();
        c = iterateChunks(c, key);

        Chunk.LookUp lookUp = c.lookUp(key);
        if (lookUp == null || lookUp.handle == null) return false;

        lookUp.handle.compute(function, null);
        return true;
    }

    @Override
    public OakMap subMap(ByteBuffer fromKey, boolean fromInclusive, ByteBuffer toKey, boolean toInclusive) {
        if (fromKey == null || toKey == null)
            throw new NullPointerException();
        return new SubOakMap(this, fromKey, fromInclusive, toKey, toInclusive, false);
    }

    @Override
    public OakMap headMap(ByteBuffer toKey, boolean inclusive) {
        if (toKey == null)
            throw new NullPointerException();
        return new SubOakMap(this, null, false, toKey, inclusive, false);
    }

    @Override
    public OakMap tailMap(ByteBuffer fromKey, boolean inclusive) {
        if (fromKey == null)
            throw new NullPointerException();
        return new SubOakMap(this, fromKey, inclusive, null, false, false);
    }

    @Override
    public OakMap descendingMap() {
        OakMap dm = descendingMap;
        return (dm != null) ? dm : (descendingMap = new SubOakMap
                (this, null, false, null, false, true));
    }


    /*-------------- Iterators --------------*/

    /**
     * Base of iterator classes:
     */
    abstract class Iter<T> implements CloseableIterator<T> {

        /**
         * the next node to return from next();
         */
        Chunk nextChunk;
        Chunk.AscendingIter nextChunkIter;
        int next;
        /**
         * Cache of next value field to maintain weak consistency
         */
        OakBuffer nextValue;

        /**
         * Initializes ascending iterator for entire range.
         */
        Iter() {
            next = Chunk.NONE;
            nextValue = null;
            initChunk();
            findNextKey();
        }

        @Override
        public void close() {

        }

        public final boolean hasNext() {
            return next != Chunk.NONE;
        }

        /**
         * Advances next to higher entry.
         */
        void advance() {
            if (next == Chunk.NONE)
                throw new NoSuchElementException();
            findNextKey();
        }

        /**
         * used only to init the iterator
         */
        private void initChunk() {
//            ByteBuffer b = constructMinKeyBuffer();
            nextChunk = skiplist.floorEntry(minKey).getValue();
            if (nextChunk == null) {
                nextChunkIter = null;
            } else {
                nextChunkIter = nextChunk.ascendingIter();
            }
        }

        /**
         * sets nextChunk, nextChunkIter, next and nextValue to the next key
         * if such a key doesn't exists then next is set to oak.Chunk.NONE and nextValue is set to null
         */
        private void findNextKey() {
            if (nextChunkIter == null) {
                return;
            }
            // find first chunk that has a valid key (chunks can have only removed keys)
            while (!nextChunkIter.hasNext()) {
                nextChunk = nextChunk.next.getReference(); // try next chunk
                if (nextChunk == null) { // there is no next chunk
                    next = Chunk.NONE;
                    nextValue = null;
                    return;
                }
                nextChunkIter = nextChunk.ascendingIter();
            }

            next = nextChunkIter.next();

            // set next value
            Handle h = nextChunk.getHandle(next);
            if (h != null) {
                nextValue = new OakBufferImpl(h);
            } else {
                nextValue = null;
            }

        }

        ByteBuffer getKey(int ki, Chunk c) {
            return c.readKey(ki);
        }

    }

    class ValueIterator extends Iter<OakBuffer> {

        public OakBuffer next() {
            OakBuffer v = nextValue;
            advance();
            return v;
        }
    }

    class EntryIterator extends Iter<Map.Entry<ByteBuffer, OakBuffer>> {

        public Map.Entry<ByteBuffer, OakBuffer> next() {
            int n = next;
            Chunk c = nextChunk;
            OakBuffer v = nextValue;
            advance();
            return new AbstractMap.SimpleImmutableEntry<>(getKey(n, c), v);
        }
    }

    class KeyIterator extends Iter<ByteBuffer> {

        public ByteBuffer next() {
            int n = next;
            Chunk c = nextChunk;
            advance();
            return getKey(n, c);
        }
    }

    // Factory methods for iterators

    @Override
    public CloseableIterator<OakBuffer> valuesIterator() {
        return new ValueIterator();
    }

    @Override
    public CloseableIterator<Map.Entry<ByteBuffer, OakBuffer>> entriesIterator() {
        return new EntryIterator();
    }

    @Override
    public CloseableIterator<ByteBuffer> keysIterator() {
        return new KeyIterator();
    }

    @Override
    public <T> CloseableIterator<T> valuesTransformIterator(Function<ByteBuffer,T> transformer) {
        throw new UnsupportedOperationException();
    }

    @Override
    public <T> CloseableIterator<T> entriesTransformIterator(Function<Map.Entry<ByteBuffer, ByteBuffer>, T> transformer) {
        throw new UnsupportedOperationException();
    }

    @Override
    public <T> CloseableIterator<T> keysTransformIterator(Function<ByteBuffer,T> transformer) {
        throw new UnsupportedOperationException();
    }


    /* ---------------- Sub Map -------------- */

    class SubOakMap implements OakMap {
        /**
         * underlying map
         */
        private final OakMapOnHeapImpl oak;
        /**
         * lower bound key, or null if from start
         */
        private final ByteBuffer lo;
        /**
         * upper bound key, or null if to end
         */
        private final ByteBuffer hi;
        /**
         * inclusion flag for lo
         */
        private final boolean loInclusive;
        /**
         * inclusion flag for hi
         */
        private final boolean hiInclusive;
        /**
         * direction
         */
        private final boolean isDescending;

        /**
         * Creates a new submap, initializing all fields.
         */
        SubOakMap(OakMapOnHeapImpl oak,
                  ByteBuffer fromKey, boolean fromInclusive,
                  ByteBuffer toKey, boolean toInclusive,
                  boolean isDescending) {
            if (fromKey != null && toKey != null &&
                    oak.comparator.compare(fromKey, toKey) > 0)
                throw new IllegalArgumentException("inconsistent range");
            this.oak = oak;
            this.lo = fromKey;
            this.hi = toKey;
            this.loInclusive = fromInclusive;
            this.hiInclusive = toInclusive;
            this.isDescending = isDescending;
        }

        /*-------------- Utilities --------------*/

        int keyCompare(ByteBuffer k1, ByteBuffer k2) {
            return oak.comparator.compare(k1, k2);
        }

        boolean tooLow(ByteBuffer key) {
            int c;
            return (lo != null && ((c = keyCompare(key, lo)) < 0 ||
                    (c == 0 && !loInclusive)));
        }

        boolean tooHigh(ByteBuffer key) {
            int c;
            return (hi != null && ((c = keyCompare(key, hi)) > 0 ||
                    (c == 0 && !hiInclusive)));
        }

        boolean inBounds(ByteBuffer key) {
            return !tooLow(key) && !tooHigh(key);
        }


        /**
         * Utility to create submaps, where given bounds override
         * unbounded(null) ones and/or are checked against bounded ones.
         */
        SubOakMap newSubOakMap(ByteBuffer fromKey, boolean fromInclusive,
                               ByteBuffer toKey, boolean toInclusive) {
            if (isDescending) { // flip senses
                ByteBuffer tk = fromKey;
                fromKey = toKey;
                toKey = tk;
                boolean ti = fromInclusive;
                fromInclusive = toInclusive;
                toInclusive = ti;
            }
            if (lo != null) {
                if (fromKey == null) {
                    fromKey = lo;
                    fromInclusive = loInclusive;
                } else {
                    int c = keyCompare(fromKey, lo);
                    if (c < 0 || (c == 0 && !loInclusive && fromInclusive))
                        throw new IllegalArgumentException("key out of range");
                }
            }
            if (hi != null) {
                if (toKey == null) {
                    toKey = hi;
                    toInclusive = hiInclusive;
                } else {
                    int c = keyCompare(toKey, hi);
                    if (c > 0 || (c == 0 && !hiInclusive && toInclusive))
                        throw new IllegalArgumentException("key out of range");
                }
            }
            return new SubOakMap(oak, fromKey, fromInclusive,
                    toKey, toInclusive, isDescending);
        }

        /*-------------- oak.OakMap Methods --------------*/

        @Override
        public void put(ByteBuffer key, ByteBuffer value) {
            oak.put(key, value);
        }

        @Override
        public boolean putIfAbsent(ByteBuffer key, ByteBuffer value) {
            return oak.putIfAbsent(key, value);
        }

        @Override
        public boolean putIfAbsent(ByteBuffer key, Consumer<ByteBuffer> valueCreator, int capacity) {
            return oak.putIfAbsent(key, valueCreator, capacity);
        }

        @Override
        public void putIfAbsentComputeIfPresent(ByteBuffer key, Supplier<ByteBuffer> constructor, Consumer<WritableOakBuffer> function) {
            oak.putIfAbsentComputeIfPresent(key, constructor, function);
        }

        @Override
        public void putIfAbsentComputeIfPresent(ByteBuffer key, Consumer<ByteBuffer> valueCreator, int capacity, Consumer<WritableOakBuffer> function) {
            oak.putIfAbsentComputeIfPresent(key, valueCreator, capacity, function);
        }

        @Override
        public void remove(ByteBuffer key) {
            if (inBounds(key)) {
                oak.remove(key);
            }
        }

        @Override
        public OakBuffer get(ByteBuffer key) {
            if (key == null) throw new NullPointerException();
            return (!inBounds(key)) ? null : oak.get(key);
        }

        @Override
        public <T> T getTransformation(ByteBuffer key, Function<ByteBuffer,T> transformer) {
            if (key == null) throw new NullPointerException();
            return (!inBounds(key)) ? null : oak.getTransformation(key, transformer);
        }

        @Override
        public boolean computeIfPresent(ByteBuffer key, Consumer<WritableOakBuffer> function) {
            return oak.computeIfPresent(key, function);
        }

        @Override
        public OakMap subMap(ByteBuffer fromKey, boolean fromInclusive, ByteBuffer toKey, boolean toInclusive) {
            if (fromKey == null || toKey == null)
                throw new NullPointerException();
            return newSubOakMap(fromKey, fromInclusive, toKey, toInclusive);
        }

        @Override
        public OakMap headMap(ByteBuffer toKey, boolean inclusive) {
            if (toKey == null)
                throw new NullPointerException();
            return newSubOakMap(null, false, toKey, inclusive);
        }

        @Override
        public OakMap tailMap(ByteBuffer fromKey, boolean inclusive) {
            if (fromKey == null)
                throw new NullPointerException();
            return newSubOakMap(fromKey, inclusive, null, false);
        }

        @Override
        public OakMap descendingMap() {
            return new SubOakMap(oak, lo, loInclusive,
                    hi, hiInclusive, !isDescending);
        }

        /*-------------- Iterators --------------*/

        abstract class SubOakMapIter<T> implements CloseableIterator<T> {

            /**
             * the next node to return from next();
             */
            Chunk nextChunk;
            Chunk.ChunkIter nextChunkIter;
            int next;
            /**
             * Cache of next value field to maintain weak consistency
             */
            OakBuffer nextValue;

            SubOakMapIter() {
                next = Chunk.NONE;
                nextValue = null;
                initChunk();
                findNextKeyInRange();
            }

            @Override
            public void close() {

            }

            public final boolean hasNext() {
                return next != Chunk.NONE;
            }

            /**
             * Advances next to higher entry.
             */
            void advance() {
                if (next == Chunk.NONE)
                    throw new NoSuchElementException();
                findNextKeyInRange();
            }

            /**
             * used only to init the iterator
             */
            private void initChunk() {
                if (!isDescending) {
                    if (lo != null)
                        nextChunk = oak.skiplist.floorEntry(lo).getValue();
                    else
                        nextChunk = oak.skiplist.floorEntry(oak.minKey).getValue();
                    if (nextChunk == null) {
                        nextChunkIter = null;
                    } else {
                        nextChunkIter = lo != null ? nextChunk.ascendingIter(lo) : nextChunk.ascendingIter();
                    }
                } else {
                    nextChunk = hi != null ? oak.skiplist.floorEntry(hi).getValue()
                            : oak.skiplist.lastEntry().getValue();
                    if (nextChunk == null) {
                        nextChunkIter = null;
                    } else {
                        nextChunkIter = hi != null ? nextChunk.descendingIter(hi, hiInclusive) : nextChunk.descendingIter();
                    }
                }
            }

            /**
             * sets nextChunk, nextChunkIter, next and nextValue to the next key in range
             * if such a key doesn't exists then next is set to oak.Chunk.NONE and nextValue is set to null
             */
            private void findNextKeyInRange() {
                if (nextChunkIter == null) {
                    return;
                }
                if (!isDescending) {
                    ascend();
                } else {
                    descend();
                }
            }

            private boolean findNextChunk() {
                while (!nextChunkIter.hasNext()) { // chunks can have only removed keys
                    nextChunk = nextChunk.next.getReference(); // try next chunk
                    if (nextChunk == null) { // there is no next chunk
                        next = Chunk.NONE;
                        nextValue = null;
                        return false;
                    }
                    nextChunkIter = nextChunk.ascendingIter();
                }
                return true;
            }

            private void ascend() {
                if (!findNextChunk()) {
                    return;
                }
                // now look for first key in range
                next = nextChunkIter.next();
                ByteBuffer key = getKey(next, nextChunk);

                while (!inBounds(key)) {
                    if (tooHigh(key)) {
                        // if we reached a key that is too high then there is no key in range
                        next = Chunk.NONE;
                        nextValue = null;
                        return;
                    }
                    if (!findNextChunk()) {
                        return;
                    }
                    next = nextChunkIter.next();
                    key = getKey(next, nextChunk);
                }
                // set next value
                Handle h = nextChunk.getHandle(next);
                if (h != null) {
                    nextValue = new OakBufferImpl(h);
                } else {
                    nextValue = null;
                }
            }

            private boolean findPrevChunk() {
                while (!nextChunkIter.hasNext()) {
                    ByteBuffer minKey = nextChunk.minKey;
                    Map.Entry e = oak.skiplist.lowerEntry(minKey);
                    if (e == null) { // there no next chunk
                        assert minKey == oak.minKey;
                        next = Chunk.NONE;
                        nextValue = null;
                        return false;
                    }
                    nextChunk = (Chunk) e.getValue();
                    Chunk nextNext = nextChunk.next.getReference();
                    if (nextNext == null) {
                        nextChunkIter = nextChunk.descendingIter(minKey, false);
                        continue;
                    }
                    ByteBuffer nextMinKey = nextNext.minKey;
                    if (nextMinKey.compareTo(minKey) < 0) {
                        nextChunk = nextNext;
                        nextMinKey = nextChunk.next.getReference().minKey;
                        while (nextMinKey.compareTo(minKey) < 0) {
                            nextChunk = nextChunk.next.getReference();
                            nextMinKey = nextChunk.next.getReference().minKey;
                        }
                    }
                    nextChunkIter = nextChunk.descendingIter(minKey, false); // TODO check correctness
                }
                return true;
            }

            private void descend() {
                if (!findPrevChunk()) {
                    return;
                }
                // now look for first key in range
                next = nextChunkIter.next();
                ByteBuffer key = getKey(next, nextChunk);

                while (!inBounds(key)) {
                    if (tooLow(key)) {
                        // if we reached a key that is too low then there is no key in range
                        next = Chunk.NONE;
                        nextValue = null;
                        return;
                    }
                    if (!findPrevChunk()) {
                        return;
                    }
                    next = nextChunkIter.next();
                    key = getKey(next, nextChunk);
                }
                nextValue = nextChunk.getHandle(next); // set next value
            }

            ByteBuffer getKey(int ki, Chunk c) {
                return c.readKey(ki);
            }

        }

        class SubOakValueIterator extends SubOakMapIter<OakBuffer> {

            public OakBuffer next() {
                OakBuffer v = nextValue;
                advance();
                return v;
            }
        }

        class SubOakEntryIterator extends SubOakMapIter<Map.Entry<ByteBuffer, OakBuffer>> {

            public Map.Entry<ByteBuffer, OakBuffer> next() {
                int n = next;
                Chunk c = nextChunk;
                OakBuffer v = nextValue;
                advance();
                ByteBuffer key = getKey(n, c);
                key = key.slice(); // TODO can I get rid of this?
                return new AbstractMap.SimpleImmutableEntry<>(key, v);
            }
        }

        class SubOakKeyIterator extends SubOakMapIter<ByteBuffer> {

            public ByteBuffer next() {
                int n = next;
                Chunk c = nextChunk;
                advance();
                ByteBuffer key = getKey(n, c);
                key = key.slice(); // TODO can I get rid of this?
                return key;
            }
        }

        // Factory methods for iterators

        @Override
        public CloseableIterator<OakBuffer> valuesIterator() {
            return new SubOakValueIterator();
        }

        @Override
        public CloseableIterator<Map.Entry<ByteBuffer, OakBuffer>> entriesIterator() {
            return new SubOakEntryIterator();
        }

        @Override
        public CloseableIterator<ByteBuffer> keysIterator() {
            return new SubOakKeyIterator();
        }

        @Override
        public <T> CloseableIterator<T> valuesTransformIterator(Function<ByteBuffer,T> transformer) {
            throw new UnsupportedOperationException();
        }

        @Override
        public <T> CloseableIterator<T> entriesTransformIterator(Function<Map.Entry<ByteBuffer, ByteBuffer>, T> transformer) {
            throw new UnsupportedOperationException();
        }

        @Override
        public <T> CloseableIterator<T> keysTransformIterator(Function<ByteBuffer,T> transformer) {
            throw new UnsupportedOperationException();
        }

    }

}
